# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "parser-wasm"
version = "0.1.0"
authors = ["LancerComet <chw644@hotmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.69"
protobuf = { version = "2.18.1" }
bytes = "0.6.0"

[build-dependencies]
protobuf-codegen-pure = "2.18.1"
protoc-rust = "2.18.1"
