# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test

on: [push, pull_request]

jobs:
  test-core-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for Core package
        working-directory: ./packages/core
        run: npm ci

      - name: Install dependencies for pixi.renderer
        working-directory: ./packages/renderer.pixi
        run: npm ci

      - name: Build Core package
        working-directory: ./packages/core
        run: npm run build --if-present
        env:
          CI: true

      - name: Run Core package testing
        working-directory: ./packages/core
        run: npm test
